hostname: "gitops-updater.local"
ingressClass: "nginx"
image: glass.azurecr.io/gitops-updater

config:
  - name: example-name
    path: directory/manifest.yaml
    secretPath: /mnt/secrets/gitops-updater-secret
    handler: argocd
    provider: my-github-repo

providers:
  - name: my-github-repo
    repository: example/repo
    branch: main
    type: GitHub
    tokenPath: /mnt/secrets/gitops-updater-github-token
  - name: my-gitlab-repo
    project: example/project
    url: https://gitlab.com
    branch: main
    type: GitLab
    tokenPath: gitlab_token

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  mountPath: "/mnt/secrets"
  secrets:
    - gitops-updater-github-token
    - gitops-updater-secret