hostname: "gitops-updater.local"
ingressClass: "nginx"
image: gitops-updater
tag: latest

config:
  - name: example-name
    path: directory/manifest.yaml
    secretPath: /mnt/secrets/gitops-updater-secret
    handler: argocd
    provider: my-github-repo

providers:
  - name: my-github-repo
    repository: example/repo
    branch: main
    type: GitHub
    tokenPath: /mnt/secrets/gitops-updater-github-token
  - name: my-gitlab-repo
    project: example/project
    url: https://gitlab.com
    branch: main
    type: GitLab
    tokenPath: gitlab_token