trigger:
  - main

pool: GLASS

jobs:
  - job: build
    steps:
      - script: |
          set -euxo pipefail
          helm lint charts/gitops-updater
        displayName: Run linter

      - script: |
          set -euxo pipefail
          docker build -t "${ACR_NAME}.azurecr.io/gitops-updater:latest" .
          docker push "${ACR_NAME}.azurecr.io/gitops-updater:latest"
        displayName: Build Docker container and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

      - script: |
          set -euxo pipefail
          VERSION="0.${BUILD_BUILDNUMBER}"
          helm package --version $VERSION --app-version $VERSION charts/gitops-updater
          helm push gitops-updater-$VERSION.tgz oci://${ACR_NAME}/helm
        displayName: Build Helm chart and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))