apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-updater-configmap
  namespace: "{{ .Release.Namespace }}"
data:
  config.yaml: |
    config:
{{- range .Values.config }}
    - name: {{ .name }}
      path: {{ .path }}
      secretPath: {{ .secretPath }}
      handler: {{ .handler }}
      provider: {{ .provider }}
{{- end }}
    providers:
    {{- range .Values.providers }}
    - name: {{ .name }}
      repository: {{ .repository }}
      branch: {{ .branch }}
      type: {{ .type }}
      tokenPath: {{ .tokenPath }}
{{- end }}
