apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-updater
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: gitops-updater
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-updater
      {{- if .Values.podLabels }}
      {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: gitops-updater
          image: "{{ .Values.image }}:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: GITOPS_UPDATER_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: GITHUB_TOKEN_PATH
              value: "{{ .Values.github_secrets_path }}"
            - name: CONFIG_PATH
              value: "/mnt/config/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}

      volumes:
        - name: config-volume
          configMap:
            name: gitops-updater-configmap
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
