apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-updater
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: gitops-updater
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-updater
      {{- if .Values.azure }}
        aadpodidbinding: gitops-updater-azure-kv
      {{- end }}
      {{- if .Values.vault }}
      annotations:
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.url }}"
        vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
        vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.path }}"
      {{- end }}
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: gitops-updater
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: GITOPS_UPDATER_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: CONFIG_PATH
              value: "/mnt/config/config.yaml"
            {{- if .Values.vault }}
            {{- range .Values.vault.secrets }}
            - name: {{ .target }}
              value: "vault:{{ $.Values.vault.path }}/data/{{ $.Values.vault.role }}#{{ .source }}"
            {{- end }}
            {{- end }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
          {{- if .Values.azure }}
            - name: secrets-store-inline
              mountPath: {{ .Values.azure.mountPath }}
              readOnly: true
          {{- end }}

      volumes:
        - name: config-volume
          configMap:
            name: gitops-updater-configmap
      {{- if .Values.azure }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "gitops-updater-secretproviderclass"
      {{- end }}
