apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-updater
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: gitops-updater
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-updater
      {{- if .Values.azure }}
        aadpodidbinding: gitops-updater-azure-kv
      {{- end }}
    spec:
      containers:
        - name: gitops-updater
          image: "{{ .Values.image }}:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: GITOPS_UPDATER_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: CONFIG_PATH
              value: "/mnt/config/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
          {{- if .Values.azure }}
            - name: secrets-store-inline
              mountPath: {{ .Values.azure.mountPath }}
              readOnly: true
          {{- end }}

      volumes:
        - name: config-volume
          configMap:
            name: gitops-updater-configmap
      {{- if .Values.azure }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "gitops-updater-secretproviderclass"
      {{- end }}
