{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-externalsecret-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled is true" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Chart.Name }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secret }}
{{- end }}