{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.registry }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-externalsecret-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled is true" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Chart.Name }}-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .Values.externalSecrets.registry.name }}":{"username":"{{ `{{ .username }}` }}","password":"{{ `{{ .password }}` }}","auth":"{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.registry.secret }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.registry.secret }}
        property: password
{{- end }}