name: build and push app

on:
  push:
    branches: [ "main" ]

env:
  CR_NAME: datanosecr.azurecr.io

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build container
      run: |
        docker build -t "${{ env.REGISTRY }}/gitops-updater:latest" .
        docker push "${{ env.REGISTRY }}/gitops-updater:latest"

    - name: Build chart and release
      env:
        UPDATER_SECRET: ${{ secrets.UPDATER_SECRET }}
      run: |
        set -euxo pipefail
        export VERSION=$(date "+0.5.%Y%m%d%H%M%S")
        helm package --version "${VERSION}" --app-version "${VERSION}" charts/gitops-updater
        helm push "gitops-updater-${VERSION}.tgz" oci://${{ env.REGISTRY }}/helm
        
        curl "https://api-v2-tst.datanose.nl/gitops-updater?name=gitops-updater&secret=${UPDATER_SECRET}&version=${VERSION}"